const gamesData = [
  {
    id: 'Infinite Tower',
    name: 'Infinite Tower',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/home/webb/',
    imgSrc: './cover/helix.webp',
  },
  {
    id: 'Build Now GG',
    name: 'Build Now GG',
    categories: ['Casual', 'Multiplayer', 'Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://buildnow-gg.io/buildnow-gg.embed',
    imgSrc: './img/buildnowgg.png',
  },
  {
    id: 'Diep IO',
    name: 'Diep IO',
    categories: ['Casual Shooter Multiplayer'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://diep.io/',
    imgSrc: './img/deepio.jpg',
  },
  {
    id: 'Tunnel Rush',
    name: 'Tunnel Rush',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/unity.html?game=https://yeet-games.github.io/games/tunnel-rush/',
    imgSrc: './cover/tunnel.webp',
  },
  {
    id: 'Space War',
    name: 'Space War',
    categories: ['Casual', 'Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/games/spac/',
    imgSrc: './cover/space.webp',
  },
  {
    id: 'Slope',
    name: 'Slope',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/slope/',
    imgSrc: './cover/slope.webp',
  },
  {
    id: 'Asteroids Belt',
    name: 'Asteroids Belt',
    categories: ['Casual', 'Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/games/spacesh/',
    imgSrc: './cover/Astr.webp',
  },
  {
    id: 'Backrooms',
    name: 'Backrooms',
    categories: ['Horror'],
    url: 'https://yeet-games.github.io/games/unity.html?game=https://yeet-games.github.io/Games/backrooms',
    imgSrc: './cover/backroom.webp',
  },
  {
    id: 'Slide In The Woods',
    name: 'Slide In The Woods',
    categories: ['Horror'],
    url: 'https://yeet-games.github.io/games/woods',
    imgSrc: './cover/Slidein.webp',
  },
  {
    id: 'Survivor Mode',
    name: 'Survivor Mode',
    categories: ['Shooter'],
    url: 'https://yeet-games.github.io/games/zombie',
    imgSrc: './cover/SurMode.webp',
  },
  {
    id: 'Stack',
    name: 'Stack',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/games/stack',
    imgSrc: './cover/Stack.webp',
  },
  {
    id: 'Fly Hydra',
    name: 'Fly Hydra',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Bin/Game_file/call/hydra',
    imgSrc: './cover/hydra.webp',
  },
  {
    id: 'Dungeon Warrior',
    name: 'Dungeon Warrior',
    categories: ['Fighting', 'Action'],
    url: 'https://yeet-games.github.io/games/dungeon',
    imgSrc: './cover/DunW.webp',
  },
  {
    id: 'Iniltrating The Airship',
    name: 'Iniltrating The Airship',
    categories: ['Casual', 'Action'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/games/henry-airship/infiltratingtheairshipgame.swf',
    imgSrc: './cover/Airship.webp',
  },
  {
    id: 'fleeing the complex',
    name: 'Fleeing The Complex',
    categories: ['Casual', 'Action'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games6/Henry%20Stickmin%20-%20Fleeing%20the%20Complex.swf',
    imgSrc: './cover/Complex.webp',
  },
  {
    id: 'Escaping The Prison',
    name: 'Escaping The Prison',
    categories: ['Casual', 'Action'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games7/escaping_the_prison.swf',
    imgSrc: './cover/Prison.webp',
  },
  {
    id: 'Breaking The Bank',
    name: 'Breaking The Bank',
    categories: ['Casual', 'Action'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games6/Henry%20Stickmin%20-%20Breaking%20the%20Bank.swf',
    imgSrc: './cover/BankH.webp',
  },
  {
    id: 'Stealing The Diamond',
    name: 'Stealing The Diamond',
    categories: ['Casual', 'Action'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games6/Henry%20Stickmin%20-%20Stealing%20the%20Diamond.swf',
    imgSrc: './cover/StealD.webp',
  },
  {
    id: 'PC Breakdown',
    name: 'PC Breakdown',
    categories: ['Casual', 'Sandbox'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games6/PC%20Breakdown.swf',
    imgSrc: './cover/PcB.webp',
  },
  {
    id: '1v1 lol',
    name: '1v1 LOL',
    categories: ['Fighting', 'Shooter', 'Multiplayer'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games-2/lol/',
    imgSrc: './cover/lol.webp',
  },
  {
    id: 'run 3',
    name: 'Run 3',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Run3/tn6pS9dCf37xAhkJv',
    imgSrc: './cover/run3s.webp',
  },
  {
    id: 'Riddle School',
    name: 'Riddle School',
    categories: ['Casual', 'Adventure'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/games/swf/riddd.swf',
    imgSrc: './cover/rid.webp',
  },
  {
    id: 'Riddle School 2',
    name: 'Riddle School 2',
    categories: ['Casual', 'Adventure'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/games/swf/riddd2.swf',
    imgSrc: './cover/rid2.webp',
  },
  {
    id: 'riddle school 3',
    name: 'Riddle School 3',
    categories: ['Casual', 'Adventure'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/games/swf/riddd3.swf',
    imgSrc: './cover/rid3.webp',
  },
  {
    id: 'riddle school 4',
    name: 'Riddle School 4',
    categories: ['Casual', 'Adventure'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/games/swf/riddd4.swf',
    imgSrc: './cover/rid4.webp',
  },
  {
    id: 'riddle school 5',
    name: 'Riddle School 5',
    categories: ['Casual', 'Adventure'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/games/swf/riddd5.swf',
    imgSrc: './cover/rid5.webp',
  },
  {
    id: 'riddle transfer',
    name: 'Riddle Transfer',
    categories: ['Casual', 'Adventure'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/games/swf/riddd6.swf',
    imgSrc: './cover/rid6.webp',
  },
  {
    id: 'riddle transfer 2',
    name: 'Riddle Transfer 2',
    categories: ['Casual', 'Adventure'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/games/swf/riddd7.swf',
    imgSrc: './cover/rid7.webp',
  },
  {
    id: 'Subway Surfers',
    name: 'Subway Surfers',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://dddavit.github.io/subway/',
    imgSrc: './cover/sub.webp',
  },
  {
    id: 'Chrome Dino',
    name: 'Chrome Dino',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/games/dino',
    imgSrc: './cover/dino.webp',
  },
  {
    id: 'tetris',
    name: 'Tetris',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/Games9/Tetris2.swf',
    imgSrc: './cover/tetris.webp',
  },
  {
    id: 'paper.io',
    name: 'Paper.io 2',
    categories: ['Casual', 'Multiplayer'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games/paperio2/index.html',
    imgSrc: './cover/paperio.webp',
  },
  {
    id: 'papas burgeria',
    name: "Papa's Burgeria",
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/FlashGames/papasburgeria.swf',
    imgSrc: './cover/papasbur.webp',
  },
  {
    id: 'papas scooperia',
    name: "Papa's Scooperia",
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games9/papasscooperia.swf',
    imgSrc: './cover/scoop.jpeg',
  },
  {
    id: 'papas sushiria',
    name: "Papa's Sushiria",
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/FlashGames/papassushiria.swf',
    imgSrc: './cover/sushiria.jpg',
  },
  {
    id: 'papas bakeria',
    name: "Papa's Bakeria",
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/FlashGames/papasbakeria.swf',
    imgSrc: './cover/bakeria.jpg',
  },
  {
    id: 'papas pastaria',
    name: "Papa's Pastaria",
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/FlashGames/papaspastaria.swf',
    imgSrc: './cover/pastaria.jpg',
  },
  {
    id: 'papas cupcakeria',
    name: "Papa's Cupcakeria",
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/FlashGames/papascupcakeria.swf',
    imgSrc: './cover/cupcakeria.jpg',
  },
  {
    id: 'papas pizzeria',
    name: "Papa's Pizzeria",
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/FlashGames/papaspizzeria_v2.swf',
    imgSrc: './cover/pizzeria.jpg',
  },
  {
    id: 'bloxorz',
    name: 'Bloxorz',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/bloxx',
    imgSrc: './cover/blox.jpeg',
  },
  {
    id: 'cookie clicker',
    name: 'Cookie Clicker',
    categories: ['Casual', 'Idle'],
    url: 'https://mr-funkinguy.github.io/cookieclicker/',
    imgSrc: './cover/click.png',
  },
  {
    id: 'agar.io',
    name: 'Agar.io',
    categories: ['Casual', 'Multiplayer'],
    url: 'https://yeet-games.github.io/games/agario',
    imgSrc: './cover/agario.jpeg',
  },
  {
    id: 'Basketball Stars',
    name: 'Basketball Stars',
    categories: ['Casual', 'Multiplayer', 'Sports'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/basketball-stars',
    imgSrc: './cover/bscLeg.avif',
  },
  {
    id: 'crossy road',
    name: 'Crossy Road',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/cr/',
    imgSrc: 'https://github.com/yeet-games/storage3/blob/main/cr.jpeg',
  },
  {
    id: 'EEL Slap',
    name: 'EEL Slap',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/storage3/eelslap/',
    imgSrc: 'https://github.com/yeet-games/storage3/blob/main/eelslap/Screenshot%202023-04-25%20at%202.35.48%20PM.png',
  },
  {
    id: 'Minecraft',
    name: 'Minecraft',
    categories: ['Casual', 'Adventure', 'Sandbox', 'Multiplayer'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/storage3/AWeb',
    imgSrc: './cover/Minecraft.png',
  },
  {
    id: 'WebGL Fluid Animation',
    name: 'WebGL Fluid Animation',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/storage3/1/',
    imgSrc: 'https://github.com/yeet-games/storage3/blob/main/1/logo.png',
  },
  {
    id: 'Funny Shooter',
    name: 'Funny Shooter',
    categories: ['Casual', 'Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/fs',
    imgSrc: 'https://github.com/yeet-games/storage3/blob/main/fs.jpeg',
  },
  {
    id: 'Geomerty Dash',
    name: 'Geomerty Dash',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games10/geodash/index.html',
    imgSrc: './cover/geo.jpeg',
  },
  {
    id: 'Bitlife',
    name: 'Bitlife',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/rating.html?game=bitlife&&url=https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games9/bitlife',
    imgSrc: './cover/Bitlife.png',
  },
  {
    id: 'A Dance of Fire And Ice',
    name: 'A Dance Of Fire And Ice',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games9/a-dance-of-fire-and-ice',
    imgSrc: 'https://raw.githubusercontent.com/Mr-funkinguy/lioxrytassets/main/other/adofai/unnamed.png',
  },
  {
    id: 'Super Hot',
    name: 'Super Hot',
    categories: ['Casual', 'Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games9/superhot/index.html',
    imgSrc: './cover/superhot.jpeg',
  },
  {
    id: 'Fnaf 1',
    name: 'FNAF',
    categories: ['Casual', 'Horror'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games9/fnaf-1/index.html',
    imgSrc: './cover/fnaf1.jpeg',
  },
  {
    id: 'Fnaf 2',
    name: 'FNAF 2',
    categories: ['Casual', 'Horror'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games4//fnaf-2/index.html',
    imgSrc: './cover/fnaf2.webp',
  },
  {
    id: 'Fnaf 3',
    name: 'FNAF 3',
    categories: ['Casual', 'Horror'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games9/fnaf-3/index.html',
    imgSrc: './cover/fnaf3.webp',
  },
  {
    id: 'Fnaf 4',
    name: 'FNAF 4',
    categories: ['Casual', 'Horror'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games9/fnaf-4/index.html',
    imgSrc: './cover/fnaf4.jpeg',
  },
  {
    id: 'fnaf sister location',
    name: 'FNAF Sister Location (Fan Made)',
    categories: ['Casual', 'Horror'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/fnafsl.html',
    imgSrc: './cover/SL1109.png',
  },
  {
    id: 'Fruit Ninja',
    name: 'Fruit Ninja',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games9/fruitninja/',
    imgSrc: './cover/FRUITNINJA.png',
  },
  {
    id: 'Uno',
    name: 'UNO',
    categories: ['Casual', 'Multiplayer'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games9/uno/index.html',
    imgSrc: './cover/uno.png',
  },
  {
    id: 'We Become What We Behold',
    name: 'We Become What We Behold',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://mr-funkinguy.github.io/gfile/wbwwb/index.html',
    imgSrc: './cover/67K.avif',
  },
  {
    id: 'dreader',
    name: 'dreader',
    categories: ['Casual', 'Horror'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://mr-funkinguy.github.io/gfile/dreader/index.html',
    imgSrc: './cover/Dreader.webp',
  },
  {
    id: 'snake',
    name: 'Snake',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://mr-funkinguy.github.io/gfile/snake/index.html',
    imgSrc: './cover/SNAKE.png',
  },
  {
    id: 'Flappy Bird',
    name: 'Flappy Bird',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://mr-funkinguy.github.io/gfile/flappy/index.html',
    imgSrc: './cover/FlappyBird.png',
  },
  {
    id: 'Mario Vs Luigi',
    name: 'Super Mario Bros. Multiplayer',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://mr-funkinguy.github.io/gfile/mariovsluigi/index.html',
    imgSrc: './cover/647K.png',
  },
  {
    id: 'SketchBook',
    name: 'Sketchbook',
    categories: ['Casual', 'Sandbox'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://mr-funkinguy.github.io/gfile/sketchbook/index.html',
    imgSrc: './cover/47K.png',
  },
  {
    id: 'Chess',
    name: 'Chess',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/games/chess/index.html',
    imgSrc: './cover/chess.png',
  },
  {
    id: 'george and the printer',
    name: 'George And the Printer',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://mr-funkinguy.github.io/gfile/georgeandtheprinter/index.html',
    imgSrc: './cover/8Jk.png',
  },
  {
    id: 'bloons Tower Defense',
    name: 'Bloons Tower Defense',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games7/bloonstd.swf',
    imgSrc: './cover/btd.png',
  },
  {
    id: 'bloons Tower Defense 3',
    name: 'Bloons Tower Defense 3',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games7/btd3.swf',
    imgSrc: './cover/btd3.png',
  },
  {
    id: 'bloons Tower Defense 4',
    name: 'Bloons Tower Defense 4',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games7/bloonstd4.swf',
    imgSrc: './cover/btd4.png',
  },
  {
    id: 'bloons Tower Defense 5',
    name: 'Bloons Tower Defense 5',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games7/btd5.swf',
    imgSrc: './cover/btd3.png',
  },
  {
    id: 'Sandboxels',
    name: 'Sandboxels',
    categories: ['Casual', 'Sandbox'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://mr-funkinguy.github.io/sandboxels',
    imgSrc: 'https://mr-funkinguy.github.io/sandboxels/icons/wallpaper.webp',
  },
  {
    id: 'Noclip',
    name: 'Noclip',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://noclip.website/',
    imgSrc: 'https://github.com/yeet-games/storage3/blob/main/NOMG.png',
  },
  {
    id: 'Street Fighter',
    name: 'Street Fighter 2',
    categories: ['Casual', 'Fighting', 'Action'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/games3/fighter2',
    imgSrc: './cover/op9p.jpeg',
  },
  {
    id: 'Smash Karts',
    name: 'Smash Karts',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://mr-funkinguy.github.io/75/projects/smashkarts/index.html',
    imgSrc: './cover/smash-karts.jpg',
  },
  {
    id: 'Combat Online',
    name: 'Combat Online',
    categories: ['Fighting', 'Action'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://unblockeds-games.com/webgl/combat-online/index.html',
    imgSrc: 'https://github.com/yeet-games/storage3/blob/main/NOMG.png',
  },
  {
    id: 'Time Shooter 2',
    name: 'Time Shooter 2',
    categories: ['Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/time-shooter-2/index.html',
    imgSrc: './cover/time-shooter-2.jpg',
  },
  {
    id: 'Happy Wheels',
    name: 'Happy Wheels',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://mrsnailman.github.io/Happy-Wheels-Source-Code/',
    imgSrc: 'https://github.com/yeet-games/storage3/blob/main/NOMG.png',
  },
  {
    id: 'Rooftop Snipers',
    name: 'Rooftop Snipers',
    categories: ['Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/games/rooftop-snipers/',
    imgSrc: './cover/rooftop-snipers.png',
  },
  {
    id: 'Cube 2',
    name: 'Cube 2',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://kripken.github.io/BananaBread/cube2/bb.html',
    imgSrc: './cover/cube2.png',
  },
  {
    id: 'Cube Engine',
    name: 'Cube Engine',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://mr-funkinguy.github.io/Cube-engine/play.html',
    imgSrc: './cover/CubeEngine.png',
  },
  {
    id: 'Super Mario 64',
    name: 'Super Mario 64',
    categories: ['Casual', 'Adventure'],
    url: 'https://yeet-games.github.io/Games2/sm64',
    imgSrc: './cover/64.jpeg',
  },
  {
    id: 'Doodle Jump',
    name: 'Doodle Jump',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://mr-funkinguy.github.io/gfile/doodle/index.html',
    imgSrc: './cover/09ML.avif',
  },
  {
    id: 'draw the hill',
    name: 'Draw The Hill',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games9/draw-the-hill/index.html',
    imgSrc: './cover/drawthehill.jpeg',
  },
  {
    id: "Five Nights at Winston's",
    name: "Five Nights at Winston's",
    categories: ['Casual', 'Horror'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games10/fnaw/index.html',
    imgSrc: 'https://github.com/yeet-games/Games10/raw/main/fnaw/splash.png',
  },
  {
    id: 'Google Feud',
    name: 'Google Feud',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://mr-funkinguy.github.io/83/google-feud/index.html',
    imgSrc: './cover/GFEUD.webp',
  },
  {
    id: 'Grey Box Testing',
    name: 'Grey Box Testing',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games9/greybox/index.html',
    imgSrc: './cover/greybox.png',
  },
  {
    id: 'Kitchen Gun',
    name: 'Kitchen Gun',
    categories: ['Casual', 'Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games10/kitchen-gun-game/index.html',
    imgSrc: 'https://github.com/yeet-games/Games10/raw/main/kitchen-gun-game/splash.png',
  },
  {
    id: 'Noob Steve Parkour',
    name: 'Noob Steve Parkour',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games10/noob-steve-parkour/index.html',
    imgSrc: 'https://github.com/yeet-games/Games10/raw/main/noob-steve-parkour/512x512.jpg',
  },
  {
    id: 'Popcat Classic',
    name: 'Popcat Classic',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games10/popcat-classic/index.html',
    imgSrc: 'https://github.com/yeet-games/Games10/raw/main/popcat-classic/splash.png',
  },
  {
    id: 'PolyBranch',
    name: 'PolyBranch',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games10/polybranch/index.html',
    imgSrc: 'https://github.com/yeet-games/Games10/raw/main/polybranch/img/pic1.png',
  },
  {
    id: 'Push Your Luck',
    name: 'Push Your Luck',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/push-your-luck/index.html',
    imgSrc: 'https://github.com/yeet-games/Games2/raw/main/push-your-luck/assets/img/push.png',
  },
  {
    id: 'Papery Planes',
    name: 'Papery Planes',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games10/papery-planes/index.html',
    imgSrc: 'https://github.com/yeet-games/Games10/raw/main/papery-planes/splash.jpg',
  },
  {
    id: 'The Heist',
    name: 'The Heist',
    categories: ['Casual', 'Driving'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games10/theheist/index.html',
    imgSrc: 'https://github.com/yeet-games/Games10/raw/main/theheist/theheist.jpg',
  },
  {
    id: 'Learn To Fly',
    name: 'Learn To Fly',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/FlashGames/learntofly.swf',
    imgSrc: './cover/ltf.png',
  },
  {
    id: 'Learn To Fly 2',
    name: 'Learn To Fly 2',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/FlashGames/learntofly2.swf',
    imgSrc: './cover/ltf2.jpg',
  },
  {
    id: 'Cat Ninja',
    name: 'Cat Ninja',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://images-opensocial.googleusercontent.com/gadgets/ifr?url=https://s3.amazonaws.com/production-assetsbucket-8ljvyr1xczmb/1ee20621-61bc-4ec8-a8ec-5e839c2e6edc%2Fcat-ninja.xml',
    imgSrc: './cover/catnin.png',
  },
  {
    id: 'moto x3m',
    name: 'Moto X3M',
    categories: ['Casual', 'Driving'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://tbg95.github.io/moto-x3m/game',
    imgSrc: './cover/motox3m.png',
  },
  {
    id: 'moto x3m 2',
    name: 'Moto X3M 2',
    categories: ['Casual', 'Driving'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/motox3m2',
    imgSrc: './cover/X3M2.png',
  },
  {
    id: 'moto x3m pool party',
    name: 'Moto X3M Pool Party',
    categories: ['Casual', 'Driving'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/motox3m-pool',
    imgSrc: './cover/X3M3.avif',
  },
  {
    id: 'moto x3m spooky land',
    name: 'Moto X3M Spooky Land',
    categories: ['Casual', 'Driving'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/motox3m-spooky',
    imgSrc: './cover/X3M9.png',
  },
  {
    id: 'moto x3m winter',
    name: 'Moto X3M Winter',
    categories: ['Casual', 'Driving'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/motox3m-winter',
    imgSrc: './cover/X3M5.jpeg',
  },
  {
    id: 'Fireboy & Watergirl 2',
    name: 'Fireboy & Watergirl 2',
    categories: ['Casual', 'Adventure', 'Multiplayer'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/FlashGames/Game11-FIRE.swf',
    imgSrc: './cover/FireW.png',
  },
  {
    id: 'Boxing Random',
    name: 'Boxing Random',
    categories: ['Casual', 'Action', 'Fighting'],
    url: 'https://tylerpalko.github.io/gamehub/boxingrandom/',
    imgSrc: './cover/NOMGG.png',
  },
  {
    id: 'CSGO Clicker',
    name: 'CSGO Clicker',
    categories: ['Casual', 'Idle'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games/CSGO-CLICKER',
    imgSrc: './cover/CSGO.png',
  },
  {
    id: 'Doom',
    name: 'Doom',
    categories: ['Shooter', 'Action'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://mr-funkinguy.github.io/wasmStuff/doom/',
    imgSrc: './cover/Doom.png',
  },
  {
    id: 'Bob The Robber 2',
    name: 'Bob The Robber 2',
    categories: ['Casual', 'Adventure'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games/bobtherobber2',
    imgSrc: './cover/bthe.jpeg',
  },
  {
    id: 'The Hotel',
    name: 'The Hotel',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games/the-hotel',
    imgSrc: './cover/thehotel.png',
  },
  {
    id: 'Sonic',
    name: 'Ultimate Flash Sonic',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/FlashGames/SONIC.swf',
    imgSrc: './cover/UFS.webp',
  },
  {
    id: 'Hacker Typer',
    name: 'Hacker Typer',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games/Hacker-Typer/',
    imgSrc: './cover/Hacker.png',
  },
  {
    id: '2048',
    name: '2048',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/20481',
    imgSrc: './cover/2048.png',
  },
  {
    id: 'Circles',
    name: 'Circles',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/circle',
    imgSrc: './cover/Circles.png',
  },
  {
    id: 'Align 4',
    name: 'Align 4',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/align-4',
    imgSrc: './cover/align4.png',
  },
  {
    id: 'Among Us',
    name: 'Among Us (Fan Made)',
    categories: ['Casual', 'Action'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/among-us',
    imgSrc: './cover/AmoungUs.jpeg',
  },
  {
    id: 'Colorun',
    name: 'Colorun',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/colorun',
    imgSrc: './cover/Coloron.jpeg',
  },
  {
    id: 'Craftmine',
    name: 'Craftmine',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/craftmine',
    imgSrc: './cover/craftmine.jpeg',
  },
  {
    id: 'Deal Or No Deal',
    name: 'Deal Or No Deal',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/deal-or-no-deal',
    imgSrc: './cover/DOND.webp',
  },
  {
    id: 'economical',
    name: 'Economical',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/economical',
    imgSrc: './cover/economicle.png',
  },
  {
    id: 'economical 2',
    name: 'Economical 2',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/economical2',
    imgSrc: './cover/Economical-2.webp',
  },
  {
    id: 'Factory Balls',
    name: 'Factory Balls',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/factoryballs',
    imgSrc: './cover/FCTYBalls.avif',
  },
  {
    id: 'Gataway Shootout',
    name: 'Gataway Shootout',
    categories: ['Shooter', 'Action'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/getaway-shootout',
    imgSrc: './cover/GTEWY.avif',
  },
  {
    id: 'Grind Craft',
    name: 'Grind Craft',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/grindcraft',
    imgSrc: './cover/GrindCraft.jpeg',
  },
  {
    id: 'madalin stunt cars 2',
    name: 'Madalin Stunt Cars 2',
    categories: ['Driving'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/madalin-stunt-cars-2',
    imgSrc: './cover/113347.jpeg',
  },
  {
    id: 'madalin stunt cars 3',
    name: 'Madalin Stunt Cars 3',
    categories: ['Driving'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/madalin-stunt-cars-3',
    imgSrc: './cover/11456.webp',
  },
  {
    id: 'q1k3',
    name: 'Q1K3',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/q1k3',
    imgSrc: './cover/q1k3.avif',
  },
  {
    id: 'Rolly Vortex',
    name: 'Rolly Vortex',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/rolly-vortex',
    imgSrc: './cover/RVortrex.png',
  },
  {
    id: 'Slope 2',
    name: 'Slope 2',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/slope-2',
    imgSrc: './cover/slope2.png',
  },
  {
    id: 'Snowbattle',
    name: 'Snowbattle.io',
    categories: ['Casual', 'Multiplayer'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/snowbattle',
    imgSrc: './cover/snowbattle.jpeg',
  },
  {
    id: 'Space Company',
    name: 'Space Company',
    categories: ['Casual', 'Idle'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/spaceCompany',
    imgSrc: './cover/spacecompany.png',
  },
  {
    id: 'Stack Bump 3D',
    name: 'Stack Bump 3D',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/stack-bump-3d',
    imgSrc: './cover/STCKB3.webp',
  },
  {
    id: 'swerve',
    name: 'Swerve',
    categories: ['Casual', 'Driving'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/swerve',
    imgSrc: './cover/swerve.webp',
  },
  {
    id: 'The Cube',
    name: 'The Cube',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/the-cube-master',
    imgSrc: './cover/TheCube.png',
  },
  {
    id: 'The Lost Ball',
    name: 'The Lost Ball',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/the-lost-ball',
    imgSrc: './cover/TheLostBall.png',
  },
  {
    id: 'Townscaper',
    name: 'Townscaper',
    categories: ['Casual', 'Sandbox'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/townscaper',
    imgSrc: './cover/townscaper.jpeg',
  },
  {
    id: 'Wordle',
    name: 'Wordle',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games2/wordle',
    imgSrc: './cover/wordle.webp',
  },
  {
    id: 'Zelda 3D',
    name: 'Zelda 3D',
    categories: ['Adventure'],
    url: 'https://yeet-games.github.io/games/Emulator.html?game=https://yeet-games.github.io/Games2/zelda3d',
    imgSrc: './cover/NOMGG.png',
  },
  {
    id: 'Doge Miner',
    name: 'Doge Miner',
    categories: ['Idle'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games4/DogeMiner',
    imgSrc: './cover/DGMINER.png',
  },
  {
    id: 'Drift Hunters',
    name: 'Drift Hunters',
    categories: ['Driving'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://webglmath.github.io/drift-hunters/',
    imgSrc: './cover/drift-hunters.png',
  },
  {
    id: 'bloxd.io',
    name: 'Bloxd.io',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://bloxd.io',
    imgSrc:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEVELx2+fF74+/tfU8rcnXYmJijckvdIAAAANElEQVR4AWMYXkAQCZAhAOYqKRkbgzjGxkpKQCEyBFxclJRCQ12AIDRUScnFhSwBFDBgAgBawjyRK2AIpQAAAABJRU5ErkJggg==', // Keep this base64 image if source is reliable
  },
  {
    id: 'Voxiom.io',
    name: 'Voxiom.io',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://voxiom.io',
    imgSrc: './cover/VOX.png',
  },
  {
    id: 'tv static',
    name: 'TV Static',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games4/tv-static',
    imgSrc: './cover/STATIC2.png',
  },
  {
    id: 'tactical weapon pack 2',
    name: 'Tactical Weapon Pack 2',
    categories: ['Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games4/tactical-weapon-pack-2',
    imgSrc: './cover/WPNPK2.png',
  },
  {
    id: 'santy is home',
    name: 'Santy Is Home',
    categories: ['Horror'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games4/santy-is-home',
    imgSrc: './cover/SANTYISHOME.png',
  },
  {
    id: 'sushi unroll',
    name: 'Sushi Unroll',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games4/sushi-unroll',
    imgSrc: './cover/UNROLL.png',
  },
  {
    id: 'super mario construct',
    name: 'Super Mario Construct',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games4/supermarioconstruct',
    imgSrc: './cover/0034.png',
  },
  {
    id: 'win the whitehouse',
    name: 'Win The Whitehouse',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games4/win-the-whitehouse',
    imgSrc: './cover/0035.png',
  },
  {
    id: 'rocket league',
    name: 'Rocket League (Clone)',
    categories: ['Driving'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games4/Rocket-League/',
    imgSrc: './cover/ROCKETL5.png',
  },
  {
    id: 'missile game',
    name: 'Missile Game',
    categories: ['Action', 'Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games4/missiles/',
    imgSrc: './cover/1094.png',
  },
  {
    id: 'merge round racers',
    name: 'Merge Round Racers',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games4/merge-round-racers/',
    imgSrc: './cover/11940.webp',
  },
  {
    id: 'frying nemo',
    name: 'Frying Nemo',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games4/frying-nemo/',
    imgSrc: './cover/1190a.png',
  },
  {
    id: 'stick duel battle',
    name: 'Stick Duel Battle',
    categories: ['Multiplayer', 'Shooter', 'Action'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games4/stick-duel-battle/',
    imgSrc: './cover/1109g.webp',
  },
  {
    id: 'super mario bros',
    name: 'Super Mario Bros',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games4/SuperMario/',
    imgSrc: './cover/091h.png',
  },
  {
    id: 'cars simulator',
    name: 'Cars Simulator',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games4/cars-simulator/',
    imgSrc: './cover/098BU.png',
  },
  {
    id: 'the worlds hardest game',
    name: 'The Worlds Hardest Game',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/Games5/swf/TheWorldsHardestGame.swf',
    imgSrc: './cover/5BL.webp',
  },
  {
    id: 'the worlds hardest game 2',
    name: 'The Worlds Hardest Game 2',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/Games5/swf/Worlds Hardest Game 2.swf',
    imgSrc: './cover/59BJ.jpeg',
  },
  {
    id: 'super smash flash',
    name: 'Super Smash Flash',
    categories: ['Action'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/Games5/swf/Super Smash Flash.swf',
    imgSrc: './cover/YU90.webp',
  },
  {
    id: 'little alchemy 2',
    name: 'Little Alchemy 2',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://littlealchemy2.com/',
    imgSrc: './cover/LACH2.jpeg',
  },
  {
    id: 'angry birds',
    name: 'Angry Birds: Slingshot Frenzy',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/AngryBirds/',
    imgSrc: './cover/0991L.webp',
  },
  {
    id: 'hexgl',
    name: 'HexGl',
    categories: ['Driving'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/HexGL-master/',
    imgSrc: './cover/HexGl.jpeg',
  },
  {
    id: 'jetpack joyride',
    name: 'Jetpack Joyride',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/jetpack-joyride/',
    imgSrc: './cover/jetpackjoyride.webp',
  },
  {
    id: 'mini shooters',
    name: 'Mini Shooters',
    categories: ['Casual', 'Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/mini-shooters/unblocked.html',
    imgSrc: './cover/MINI109.png',
  },
  {
    id: 'pixel gun apocalypse 2',
    name: 'Pixel Gun Apocalypse 2',
    categories: ['Shooter', 'Action'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/pixelgun/',
    imgSrc: './cover/PIXEL901.png',
  },
  {
    id: '99balls',
    name: '99 Balls',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/99balls/',
    imgSrc: './cover/99balls.avif',
  },
  {
    id: '9007199254740992',
    name: '9007199254740992',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/9007199254740992/',
    imgSrc: './cover/9900ER.png',
  },
  {
    id: 'angry sharks',
    name: 'Angry Sharks',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/angry-sharks/',
    imgSrc: './cover/00LM2.png',
  },
  {
    id: 'station 141',
    name: 'Station 141',
    categories: ['Casual', 'Action'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/station-141/',
    imgSrc: './cover/ST141.png',
  },
  {
    id: 'pipe riders',
    name: 'Pipe Riders',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/pipe-riders',
    imgSrc: './cover/098B.png',
  },
  {
    id: 'adventure drivers',
    name: 'Adventure Drivers',
    categories: ['Adventure', 'Driver'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/adventure-drivers',
    imgSrc: './cover/0098K.avif',
  },
  {
    id: 'amazing rope police',
    name: 'Amazing Rope Police',
    categories: ['Casual', 'Action'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/amazing-rope-police',
    imgSrc: './cover/098M.png',
  },
  {
    id: '10 minutes till dawn',
    name: '10 Minutes Till Dawn',
    categories: ['Adventure', 'Action'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/10-minutes-till-dawn',
    imgSrc: './cover/10MINB.webp',
  },
  {
    id: 'cut the rope',
    name: 'Cut The Rope',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/ctr',
    imgSrc: './cover/ctr.png',
  },
  {
    id: 'cut the rope 2',
    name: 'Cut The Rope 2',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/ctr-holiday',
    imgSrc: './cover/ctr2.png',
  },
  {
    id: 'cut the rope 3',
    name: 'Cut The Rope 3',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/ctr-tr',
    imgSrc: './cover/tr3.png',
  },
  {
    id: 'defend the tank',
    name: 'Defend The Tank',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/defend-the-tank',
    imgSrc: './cover/098MN.jpeg',
  },
  {
    id: 'bad ice cream',
    name: 'Bad Ice Cream',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/bad-ice-cream',
    imgSrc: './cover/BICEC.png',
  },
  {
    id: 'bad ice cream 2',
    name: 'Bad Ice Cream 2',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/bad-ice-cream-2',
    imgSrc: './cover/BICEC2.webp',
  },
  {
    id: 'bad ice cream 3',
    name: 'Bad Ice Cream 3',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/bad-ice-cream-3',
    imgSrc: './cover/BICEC3.png',
  },
  {
    id: 'storm the house 2',
    name: 'Storm The House 2',
    categories: ['Casual', 'Action'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/Games5/stormthehouse2/StormtheHouse2.swf',
    imgSrc: './cover/stormthehouse2.jpg',
  },
  {
    id: 'highway justice',
    name: 'Highway Justice',
    categories: ['Casual', 'Driver'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/Games5/highway-justice.swf',
    imgSrc: './cover/09KL.jpeg',
  },
  {
    id: 'drive mad',
    name: 'Drive Mad',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/drive-mad',
    imgSrc: './cover/drive-mad.jpg',
  },
  {
    id: 'connect 3',
    name: 'Connect 3',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/connect3',
    imgSrc: './cover/connect3.png',
  },
  {
    id: 'stickman hook',
    name: 'Stickman Hook',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/stickman-hook',
    imgSrc: './cover/890P.jpeg',
  },
  {
    id: 'champion island',
    name: 'Champion Island',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/champion-island',
    imgSrc: './cover/0091GH.jpeg',
  },
  {
    id: 'wordle',
    name: 'Wordle',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/wordle',
    imgSrc: './cover/WORDLEE.jpeg',
  },
  {
    id: 'ovo',
    name: 'OvO',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games5/ovo',
    imgSrc: './cover/OVO.png',
  },
  {
    id: 'The Battle',
    name: 'The Battle',
    categories: ['Casual', 'Action', 'Shooter'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/Games5/thebattle.swf',
    imgSrc: './cover/eer6.png',
  },
  {
    id: 'Highway Racer',
    name: 'Highway Racer',
    categories: ['Driver'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/hwy-rcer',
    imgSrc: './cover/hwy-rcer.png',
  },
  {
    id: 'roommate',
    name: 'Roommate',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/roommate/31',
    imgSrc: './cover/PO09.png',
  },
  {
    id: '1v1 space',
    name: '1v1 Space',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/1v1space',
    imgSrc: './cover/CLOUDS.png',
  },
  {
    id: 'untitled zombie game',
    name: 'Untitled Zombie Game',
    categories: ['Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://v6p9d9t4.ssl.hwcdn.net/html/8805247/UZG/index.html',
    imgSrc: './cover/UZG.png',
  },
  {
    id: 'cupcake 2048',
    name: 'Cupcake 2048',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/cupcake2048',
    imgSrc: './cover/2048CC.png',
  },
  {
    id: 'evil glitch',
    name: 'Evil Glitch',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/evil-glitch',
    imgSrc: './cover/EVILG.jpeg',
  },
  {
    id: 'cannon basketball 4',
    name: 'Cannon Basketball 4',
    categories: ['Sports'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/cannon-basketball-4',
    imgSrc: './cover/CANNONBSKT.png',
  },
  {
    id: 'dragon vs bricks',
    name: 'Dragon Vs Bricks',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/dragon-vs-bricks',
    imgSrc: './cover/67OPY.webp',
  },
  {
    id: 'drift boss',
    name: 'Drift Boss',
    categories: ['Casual', 'Driver'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/drift-boss',
    imgSrc: './cover/DRIFTBOSS.jpeg',
  },
  {
    id: 'eggy car',
    name: 'Eggycar',
    categories: ['Casual', 'Driver'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/eggycar',
    imgSrc: './cover/EGGYCAR.webp',
  },
  {
    id: 'blockpost',
    name: 'Blockpost',
    categories: ['Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/blockpost',
    imgSrc: './cover/BLOCKPOST.avif',
  },
  {
    id: 'portal flash',
    name: 'Portal Flash',
    categories: ['Casual', 'Adventure'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/Games6/portal.swf',
    imgSrc: './cover/PORTALF.png',
  },
  {
    id: 'ice age baby',
    name: 'Ice Age Baby',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/unity.html?game=https://yeet-games.github.io/Games6/iceagebaby',
    imgSrc: './cover/ICEAGEBABY.png',
  },
  {
    id: 'black hole square',
    name: 'Black Hole Square',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/blacholesquare',
    imgSrc: './cover/BLACKHOLESQ.png',
  },
  {
    id: 'virtual os',
    name: 'Virtual OS',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/vmlinux',
    imgSrc: './cover/VM78.png',
  },
  {
    id: '30 dollar website',
    name: '30 Dollar Website',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/30dollarwebsite',
    imgSrc: './cover/30dollarwebsite.png',
  },
  {
    id: 'gun mayhem',
    name: 'Gun Mayhem',
    categories: ['Shooter', 'Action'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/Games6/gun-mayhem.swf',
    imgSrc: './cover/GMYHM.png',
  },
  {
    id: 'gun mayhem 2',
    name: 'Gun Mayhem 2',
    categories: ['Shooter', 'Action'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/Games6/gun-mayhem-2.swf',
    imgSrc: './cover/GMYHM.png',
  },
  {
    id: 'animator vs animation',
    name: 'Animator Vs Animation',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/Games6/animatorvsanimation.swf',
    imgSrc: './cover/ANMVS.png',
  },
  {
    id: 'ballistic chickens',
    name: 'Ballistic Chickens',
    categories: ['Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/ballistic-chickens',
    imgSrc: './cover/BCHK.png',
  },
  {
    id: 'big red button',
    name: 'Big Red Button',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/bigredbutton',
    imgSrc: './cover/BRB5.png',
  },
  {
    id: 'burger and frights',
    name: 'Burger And Frights',
    categories: ['Horror'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/burger-and-frights',
    imgSrc: './cover/BAFy.jpeg',
  },
  {
    id: 'zombotron',
    name: 'Zombotron',
    categories: ['Shooter', 'Horror'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/zombotron',
    imgSrc: './cover/zombotron.webp',
  },
  {
    id: 'jelly truck',
    name: 'Jelly Truck',
    categories: ['Driver'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/jellytruck',
    imgSrc: './cover/JELLYTRCK.png',
  },
  {
    id: 'wheely 6',
    name: 'Wheely 6',
    categories: ['Driver'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/wheely6',
    imgSrc: './cover/wheely6.png',
  },
  {
    id: 'google solitaire',
    name: 'Google Solitaire',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/google-solitaire',
    imgSrc: './cover/google-solitaire.png',
  },
  {
    id: '8 ball',
    name: '8 Ball',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/8ball',
    imgSrc: './cover/8ball.png',
  },
  {
    id: 'jacksmith',
    name: 'Jacksmith',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/Games6/jacksmith.swf',
    imgSrc: './cover/890Bml.png',
  },
  {
    id: 'dont fall io',
    name: 'Dont Fall .io',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/dont-fall-io',
    imgSrc: './cover/DNTFLL.png',
  },
  {
    id: 'space cadet pinball',
    name: 'Space Cadet Pinball',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/space-cadet-pinball/',
    imgSrc: './cover/SPACECADET.png',
  },
  {
    id: 'the maze',
    name: 'The Maze',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/Games6/themazev1.1.swf',
    imgSrc: './cover/MAZE3.png',
  },
  {
    id: 'rolling sky',
    name: 'Rolling Sky',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/webgl-rollingsky/',
    imgSrc: './cover/SKYRO.png',
  },
  {
    id: 'time shooter 3',
    name: 'Time Shooter 3 S.W.A.T',
    categories: ['Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/timeshoot3/',
    imgSrc: './cover/SWATSH.png',
  },
  {
    id: 'fancy pants adventure',
    name: 'Fancy Pants Adventure',
    categories: ['Adventure'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/Games6/fancypantsadventures/fancypantsadventure.swf',
    imgSrc: './cover/FANCYADV.png',
  },
  {
    id: 'basket and ball',
    name: 'Basket And Ball',
    categories: ['Sports'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/basketandball',
    imgSrc: './cover/BASKETAND.png',
  },
  {
    id: 'parking fury 3',
    name: 'Parking And Fury 3',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/parking-fury-3',
    imgSrc: './cover/PARKINGFUR.png',
  },
  {
    id: 'snake.io',
    name: 'Snake.io',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/snakeio',
    imgSrc: './cover/SNAKEIO.png',
  },
  {
    id: 'stickman epic battle',
    name: 'Stickman Epic Battle',
    categories: ['Action'],
    url: 'https://yeet-games.github.io/games/unity.html?game=https://yeet-games.github.io/Games6/stickman-epic-battle',
    imgSrc: './cover/STICKMANEPIC.png',
  },
  {
    id: 'sort the court',
    name: 'Sort The Court',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/unity.html?game=https://yeet-games.github.io/Games6/sort-the-court',
    imgSrc: './cover/SORTTHECOURT.png',
  },
  {
    id: 'shuttle deck',
    name: 'Shuttle Deck',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/shuttledeck',
    imgSrc: './cover/SHUTTLEDECK.png',
  },
  {
    id: 'sans fight',
    name: 'Sans Fight',
    categories: ['Action'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/sansfight',
    imgSrc: './cover/SANSFIGHT.png',
  },
  {
    id: 'sand game',
    name: 'Sand Game',
    categories: ['Sandbox'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/sand-game',
    imgSrc: './cover/SANDGAME.png',
  },
  {
    id: 'oregon trail game',
    name: 'Oregon Trail Game',
    categories: ['Adventure'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/oregon-trail-game-master/',
    imgSrc: './cover/OREGONB.png',
  },
  {
    id: 'idle shark',
    name: 'Idle Shark',
    categories: ['Idle'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/idle-shark/',
    imgSrc: './cover/IDLESHARK.png',
  },
  {
    id: 'death run 3d',
    name: 'Death Run 3D',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/death-run-3d/',
    imgSrc: './cover/DEATHRUN.png',
  },
  {
    id: 'clean up io',
    name: 'Clean Up.io',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/unity.html?game=https://yeet-games.github.io/Games6/clean-up-io/',
    imgSrc: './cover/CLEANUP.png',
  },
  {
    id: 'online racing game',
    name: 'Online Racing Game',
    categories: ['Driver'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/cars-master/',
    imgSrc: './cover/CARSMASTER.png',
  },
  {
    id: 'baldis basics',
    name: 'Baldis Basics',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/baldis-basics/',
    imgSrc: './cover/BALDIS.png',
  },
  {
    id: 'starwars movie',
    name: 'Starwars Movie',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/StarWarsMovie.html',
    imgSrc: './cover/STARWARS.png',
  },
  {
    id: 'drift city',
    name: 'Drift City',
    categories: ['Casual', 'Driver'],
    url: 'https://yeet-games.github.io/games/unity.html?game=https://yeet-games.github.io/Games6/drift-city',
    imgSrc: './cover/DRIFTCITY.png',
  },
  {
    id: 'google baseball',
    name: 'Google Baseball',
    categories: ['Sports'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/google-baseball',
    imgSrc: './cover/BASEBALLG.png',
  },
  {
    id: 'horde killer',
    name: 'Horde Killer',
    categories: ['Shooter'],
    url: 'https://yeet-games.github.io/games/unity.html?game=https://yeet-games.github.io/Games6/horde-killer',
    imgSrc: './cover/HORDEKILLER.png',
  },
  {
    id: 'timothys race',
    name: 'Timothys Race',
    categories: ['Driver'],
    url: "https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games6/timothy's-race",
    imgSrc: './cover/TIMRACE.png',
  },
  {
    id: 'slowroads',
    name: 'Slowroads',
    categories: ['Casual', 'Driver'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/slowroads',
    imgSrc: './cover/SLOWROADS.png',
  },
  {
    id: 'Tactical Assasin 2',
    name: 'Tactical Assasin 2',
    categories: ['Shooter'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=/Games7/tacticalassasin2.swf',
    imgSrc: './cover/TACASSASIN.png',
  },
  {
    id: 'web osu',
    name: 'Web OSU',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/osu',
    imgSrc: './cover/OSU.webp',
  },
  {
    id: 'very very plane',
    name: 'Very Very Plane',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/unity.html?game=https://yeet-games.github.io/Games7/vvplane',
    imgSrc: './cover/VVPLANE.png',
  },
  {
    id: 'tiny fishing',
    name: 'Tiny Fishing',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/tiny-fishing',
    imgSrc: './cover/TINYFISH.png',
  },
  {
    id: 'waterworks',
    name: 'Waterworks',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/waterworks',
    imgSrc: './cover/WWH.png',
  },
  {
    id: 'vex3',
    name: 'Vex 3',
    categories: ['Casual', 'Adventure'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/vex3',
    imgSrc: './cover/vex3.png',
  },
  {
    id: 'vex4',
    name: 'Vex 4',
    categories: ['Casual', 'Adventure'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/vex4',
    imgSrc: './cover/vex3.png',
  },
  {
    id: 'vex5',
    name: 'Vex 5',
    categories: ['Casual', 'Adventure'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/vex5',
    imgSrc: './cover/vex3.png',
  },
  {
    id: 'vex6',
    name: 'Vex 6',
    categories: ['Casual', 'Adventure'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/vex6',
    imgSrc: './cover/vex3.png',
  },
  {
    id: 'vex7',
    name: 'Vex 7',
    categories: ['Casual', 'Adventure'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/vex3', // Note: This URL is the same as Vex 3. Check if this is correct.
    imgSrc: './cover/vex3.png',
  },
  {
    id: 'fake update',
    name: 'Fake Update',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://mr-funkinguy.github.io/MENU',
    imgSrc: './cover/FAKEUP.png',
  },
  {
    id: 'black hole io',
    name: 'BlackHole.io',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/eatio',
    imgSrc: './cover/HOLEIO.png',
  },
  {
    id: 'flappy 2048',
    name: 'Flappy 2048',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/flappy-2048',
    imgSrc: './cover/FLAPPY2048.png',
  },
  {
    id: 'gravity soccer',
    name: 'Gravity Soccer',
    categories: ['Casual', 'Sports'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/gravity-soccer',
    imgSrc: './cover/GRAVSOCCER.png',
  },
  {
    id: 'just fall',
    name: 'Just Fall',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/just-fall',
    imgSrc: './cover/JSTFALL.png',
  },
  {
    id: 'steal this election',
    name: 'Steal This Election',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/steal-this-election',
    imgSrc: './cover/STEALTE.png',
  },
  {
    id: 'webretro',
    name: 'Web Retro Emulator',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/webretro',
    imgSrc: './cover/WEBRETRO.png',
  },
  {
    id: 'x trial racing',
    name: 'X Trial Racing',
    categories: ['Driver'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/x-trial-racing',
    imgSrc: './cover/XTRIAL.png',
  },
  {
    id: 'big tower tiny square',
    name: 'Big Tower Tiny Square',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/btts',
    imgSrc: './cover/BTTS.png',
  },
  {
    id: 'offline Paradise',
    name: 'Offline Paradise',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/OfflineParadise',
    imgSrc: './cover/OFFP.png',
  },
  {
    id: 'very normal shooter',
    name: 'Very Normal Shooter',
    categories: ['Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/verynormalshooter',
    imgSrc: './cover/VERYNORSH.png',
  },
  {
    id: 'mindustry',
    name: 'Mindustry',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/mindustry',
    imgSrc: './cover/MINEDUST.png',
  },
  {
    id: 'miniputt',
    name: 'Miniputt',
    categories: ['Sports', 'Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games7/miniputt.swf',
    imgSrc: './cover/miniputt.png',
  },
  {
    id: 'cubefield',
    name: 'Cube Field',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/cubefield',
    imgSrc: './cover/CUBEF.png',
  },
  {
    id: 'ball hop',
    name: 'Ball Hop',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/ball-hop',
    imgSrc: './cover/ballhop.png',
  },
  {
    id: 'sky car stunt',
    name: 'Sky Car Stunt',
    categories: ['Driver'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/sky-car-stunt',
    imgSrc: './cover/SKYCARSTUNT.png',
  },
  {
    id: 'slime rush tower defence',
    name: 'Slime Rush Tower Defence',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/slime-rush-td',
    imgSrc: './cover/SLIMERUSH.png',
  },
  {
    id: 'blackjack',
    name: 'Blackjack',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/blackjack',
    imgSrc: './cover/BLACKJACK.png',
  },
  {
    id: 'biters io',
    name: 'Biters Io',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/biters-io',
    imgSrc: './cover/BITERS.png',
  },
  {
    id: 'matrix rampage',
    name: 'Matrix Rampage',
    categories: ['Shooter'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games7/matrixrampage.swf',
    imgSrc: './cover/MATRIXR.png',
  },
  {
    id: 'weavesilk',
    name: 'Weavesilk',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/weavesilk/',
    imgSrc: './cover/weavesilk.png',
  },
  {
    id: 'train ride',
    name: 'Train Ride',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/trainride/',
    imgSrc: './cover/trainride.png',
  },
  {
    id: 'tower master',
    name: 'Tower Master',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/towermaster/',
    imgSrc: './cover/towermaster.png',
  },
  {
    id: 'station meltdown',
    name: 'Station Meltdown',
    categories: ['Action'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/station-meltdown/',
    imgSrc: './cover/stationmelt.png',
  },
  {
    id: 'stackball',
    name: 'Stackball',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/stackball/',
    imgSrc: './cover/stackball.png',
  },
  {
    id: 'snow rider',
    name: 'Snow Rider 3D',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/snow-rider3d/',
    imgSrc: './cover/snowrider.png',
  },
  {
    id: 'small world cup',
    name: 'Small World Cup',
    categories: ['Casual', 'Sports'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/smallworldcup/',
    imgSrc: './cover/smallwrld.png',
  },
  {
    id: 'pokey stick',
    name: 'Pokey Stick',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/pokey-stick/',
    imgSrc: './cover/stickpo.png',
  },
  {
    id: 'gun spinn',
    name: 'Gun Spinn',
    categories: ['Casual', 'Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/gunspinn/',
    imgSrc: './cover/gunnn.png',
  },
  {
    id: 'breaklock',
    name: 'Breaklock',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/breaklock/',
    imgSrc: './cover/BREAKLOCK.png',
  },
  {
    id: 'gopher kart',
    name: 'Gopher Kart',
    categories: ['Driver'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/gopher-kart',
    imgSrc: './cover/gopherkart.png',
  },
  {
    id: 'mario combat',
    name: 'Mario Combat',
    categories: ['Action'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games7/Mario_Combat.swf',
    imgSrc: './cover/MARIOK.png',
  },
  {
    id: 'color combat',
    name: 'Color Combat',
    categories: ['Action'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games7/color_combat.swf',
    imgSrc: './cover/COLORCOM.png',
  },
  {
    id: 'microsoft flight simulator',
    name: 'MS Flight Sim 1-4',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/msflight/',
    imgSrc: './cover/MS4.png',
  },
  {
    id: 'nightwalk',
    name: 'Nightwalk',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/nightwalk/',
    imgSrc: './cover/nightwalk.png',
  },
  {
    id: 'pong',
    name: 'Pong',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games7/pong.swf',
    imgSrc: './cover/pong.png',
  },
  {
    id: 'dont touch anything',
    name: 'Dont Touch Anything',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/touch/',
    imgSrc: './cover/dontouch.png',
  },
  {
    id: 'gun master',
    name: 'Gun Master',
    categories: ['Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/gun-master/',
    imgSrc: './cover/GUNMASTER.png',
  },
  {
    id: '10-103',
    name: '10-103',
    categories: ['Adventure', 'Shooter', 'Horror'],
    url: 'https://yeet-games.github.io/games/unity.html?game=https://yeet-games.github.io/Games7/10-103/',
    imgSrc: './cover/10103.png',
  },
  {
    id: 'fear the spotlight',
    name: 'Fear The Spotlight',
    categories: ['Horror'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/fearthespotlight/',
    imgSrc: './cover/FEARTHESPOT.png',
  },
  {
    id: 'pandemic 2',
    name: 'Pandemic 2',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games7/pandemic2.swf',
    imgSrc: './cover/PANDEM2.png',
  },
  {
    id: 'thermomorph',
    name: 'Thermomorph',
    categories: ['Horror'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/thermomorph/',
    imgSrc: './cover/THERMO.png',
  },
  {
    id: 'raftwars',
    name: 'Raftwars',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games7/raftwars.swf',
    imgSrc: './cover/RAFTWARS.png',
  },
  {
    id: 'getting over it',
    name: 'Getting Over It Scratch Edition',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/getting-over-it',
    imgSrc: './cover/gettingoverit.png',
  },
  {
    id: 'radius raid',
    name: 'Radius Raid',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/radius-raid',
    imgSrc: './cover/RADIUSRAID.png',
  },
  {
    id: 'roadblocks',
    name: 'Roadblocks',
    categories: ['Casual', 'Sandbox'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/roadblocks',
    imgSrc: './cover/ROADBLOCKS.png',
  },
  {
    id: 'edge not found',
    name: 'Edge Not Found',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/edgenotfound',
    imgSrc: './cover/EDGENOTFOUND.png',
  },
  {
    id: 'cyber city driver',
    name: 'Cyber City Driver',
    categories: ['Driver'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/cyber-city-driver',
    imgSrc: './cover/CYBERCITYD.png',
  },
  {
    id: 'creative kill chamber',
    name: 'Creative Kill Chamber',
    categories: ['Casual', 'Shooter'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games7/creativekillchamber.swf',
    imgSrc: './cover/23CkillC.png',
  },
  {
    id: 'make sure its closed',
    name: 'Make Sure Its Closed',
    categories: ['Horror'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games7/makesureitsclosed',
    imgSrc: './cover/MSIC.png',
  },
  {
    id: 'kids vs icecream',
    name: 'Kids Vs Icecream',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games8/kids_vs_icecream.swf',
    imgSrc: './cover/KIDSVSICECREAM.png',
  },
  {
    id: 'battle for gondor',
    name: 'Battle For Gondor',
    categories: ['Action', 'Adventure'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games8/battle-for-gondor.swf',
    imgSrc: './cover/BATTLEFORGONDOR.png',
  },
  {
    id: 'cell machine',
    name: 'Cell Machine',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/cell-machine',
    imgSrc: './cover/CELLMACHINE.png',
  },
  {
    id: 'donut boy',
    name: 'Donut Boy',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/donut-boy',
    imgSrc: './cover/DONUTBOY.png',
  },
  {
    id: 'yoshi fabrication',
    name: 'Yoshi Fabrication',
    categories: ['Adventure'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/yoshifabrication',
    imgSrc: './cover/YOSHIFABR.png',
  },
  {
    id: 'you vs 100 skibidi toilets',
    name: 'You Vs 100 Skibidi Toilets',
    categories: ['Shooter'],
    url: 'https://yeet-games.github.io/games/unity.html?game=https://yeet-games.github.io/Games8/youvs100SK',
    imgSrc: './cover/YOUVSSK.png',
  },
  {
    id: 'paper fold',
    name: 'Paper Fold',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/paper-fold',
    imgSrc: './cover/PAPERFOLD.png',
  },
  {
    id: 'president simulator',
    name: 'President Simulator',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/president-simulator',
    imgSrc: './cover/PRESSIM.png',
  },
  {
    id: 'only up clone',
    name: 'Only Up Clone',
    categories: ['Casual', 'Adventure'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/only-up',
    imgSrc: './cover/ONLYUPCLONE.png',
  },
  {
    id: 'funny battle 2',
    name: 'Funny Battle 2',
    categories: ['Casual', 'Sandbox', 'Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/FUNNYBATTLE2',
    imgSrc: './cover/FUNNYBATTLE2.png',
  },
  {
    id: 'zombie shooter',
    name: 'Zombie Shooter',
    categories: ['Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/ZOMBIESHOOTER',
    imgSrc: './cover/ZOMBIESHOOTER.png',
  },
  {
    id: 'sniper shot bullet time',
    name: 'Sniper Shot: Bullet Time',
    categories: ['Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/SNIPERFIXED',
    imgSrc: './cover/SNIPERSHOTBT.png',
  },
  {
    id: 'neon flytron',
    name: 'Neon Flytron: Cyberpunk Racer',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/NEONFLYTRON',
    imgSrc: './cover/NEOFLYTRON.png',
  },
  {
    id: 'zombie shooter',
    name: 'Zombie Shooter: Wave Of Zombies',
    categories: ['Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/ZOMBIESHOOTERWAVEOFZOMS',
    imgSrc: './cover/ZOMBIESHOOTERWAVE.png',
  },
  {
    id: 'flip the gun',
    name: 'Flip The Gun',
    categories: ['Casual', 'Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/FLIPTHEGUN',
    imgSrc: './cover/FLIPTHEGUNSH.png',
  },
  {
    id: 'city driver',
    name: 'City Driver',
    categories: ['Casual', 'Driver'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/CITYDRIVER',
    imgSrc: './cover/CITYDRIVER.png',
  },
  {
    id: 'airbattle',
    name: 'AirBattle',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/AIRBATTLE',
    imgSrc: './cover/AIRBATTLE.png',
  },
  {
    id: '3d noob destroyer',
    name: '3D Noob Destroyer',
    categories: ['Casual', 'Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/3DNOOBDESTROYER',
    imgSrc: './cover/3DnoobD.png',
  },
  {
    id: 'granny',
    name: 'Granny Clone',
    categories: ['Horror', 'Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/GRANNY',
    imgSrc: './cover/GRANNY.png',
  },
  {
    id: 'builder',
    name: 'Builder',
    categories: ['Casual', 'Sandbox'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/BUILDER',
    imgSrc: './cover/BUILDERV.png',
  },
  {
    id: 'ultimate destruction simulator',
    name: 'Ultimate Destruction Simulator',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/ULTIMATEDS',
    imgSrc: './cover/ULDSl.png',
  },
  {
    id: 'going balls',
    name: 'Going Balls',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/goingballs',
    imgSrc: './cover/GOINGBALLS.png',
  },
  {
    id: 'build bridges',
    name: 'Build Bridges',
    categories: ['Casual', 'Sandbox'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/BUILDBRIDGES',
    imgSrc: './cover/BUILDBRIDGES.png',
  },
  {
    id: 'stickman tour kart',
    name: 'Stickman Tour Kart',
    categories: ['Driver'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/STICKMANTOURKART',
    imgSrc: './cover/STICKMANTK.png',
  },
  {
    id: 'money rush',
    name: 'Money Rush',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/MONEYRUSH',
    imgSrc: './cover/MONEYRUSH.png',
  },
  {
    id: 'draw drive',
    name: 'Draw Drive',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games8/DRAWDRIVE',
    imgSrc: './cover/DRAWDRIVE.png',
  },
  {
    id: 'marvel vs capcom',
    name: 'Marvel Vs Capcom',
    categories: ['Action'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games9/MARVELVSCAPCOM',
    imgSrc: './cover/MVSCAPCOM.png',
  },
  {
    id: 'tanuki sunset',
    name: 'Tanuki Sunset',
    categories: ['Driver'],
    url: 'https://yeet-games.github.io/games/unity.html?game=https://yeet-games.github.io/Games9/TANUKISUNSET',
    imgSrc: './cover/TANUKISUNSET.png',
  },
  {
    id: 'bango cat',
    name: 'Bango Cat',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games9/BANGOCAT',
    imgSrc: './cover/BANGOCAT.png',
  },
  {
    id: 'music ball',
    name: 'Music Ball',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/unity.html?game=https://yeet-games.github.io/Games9/MUSICBALL',
    imgSrc: './cover/MUSICBALL.png',
  },
  {
    id: 'tomb of the mask',
    name: 'Tomb of The Mask',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/unity.html?game=https://yeet-games.github.io/Games9/tomb',
    imgSrc: './cover/tomball.png',
  },
  {
    id: 'roblox',
    name: 'Roblox',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/roblox.html',
    imgSrc: './cover/roblox.jpeg',
  },
  {
    id: 'cyber tunnel',
    name: 'Cyber Tunnel',
    categories: ['Driver'],
    url: 'https://yeet-games.github.io/games/unity.html?game=https://yeet-games.github.io/Games9/CYBERTUNNEL',
    imgSrc: './cover/cybertun.png',
  },
  {
    id: 'exo',
    name: 'EXO',
    categories: ['Casual', 'Sandbox', 'Idle'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games9/EXO',
    imgSrc: './cover/EXOOO.png',
  },
  {
    id: 'minecraft tower defence',
    name: 'Minecraft Tower Defence',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games9/mftd.swf',
    imgSrc: './cover/mtd.png',
  },
  {
    id: 'minecraft tower defence 2',
    name: 'Minecraft Tower Defence 2',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/Flash.html?game=https://yeet-games.github.io/Games9/mftd2.swf',
    imgSrc: './cover/mtd2.png',
  },
  {
    id: 'the bowling club',
    name: 'The Bowling Club',
    categories: ['Casual'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games9/thebowlingclub/',
    imgSrc: './cover/thebowlingclub.png',
  },
  {
    id: 'hard golf',
    name: 'Hard Golf',
    categories: ['Casual', 'Sports'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games9/HARDGOLF/',
    imgSrc: './cover/hardgolf.png',
  },
  {
    id: 'archer hero',
    name: 'Archer Hero',
    categories: ['Casual', 'Shooter'],
    url: 'https://yeet-games.github.io/games/game.html?game=https://yeet-games.github.io/Games9/archer-hero/unblocked',
    imgSrc: './cover/0987N.png',
  },
  // New games
  {
    id: 'bottle flip',
    name: 'Bottle Flip',
    categories: ['Casual'],
    url: './games/game.html?game=/Games11/bottle-flip/game',
    imgSrc: './cover/bottleflip.jpg',
  },
  {
    id: 'drift boss fix',
    name: 'Drift Boss FIX',
    categories: ['Driver'],
    url: './games/game.html?game=/Games11/drift-boss/game',
    imgSrc: './cover/driftbosss.jpg',
  },
  {
    id: 'retro bowl',
    name: 'Retro Bowl',
    categories: ['Casual', 'Sports'],
    url: './games/game.html?game=/Games11/retro-bowl/game',
    imgSrc: './cover/retrobowl.avif',
  },
  {
    id: 'crazy cars',
    name: 'Crazy Cars',
    categories: ['Casual', 'Driver'],
    url: './games/game.html?game=/Games11/crazy-cars/game',
    imgSrc: './cover/crazycars.jpg',
  },
  {
    id: 'blumgi rocket',
    name: 'Blumgi Rocket',
    categories: ['Casual'],
    url: './games/game.html?game=/Games11/blumgi-rocket/game',
    imgSrc: './cover/NOMGG.png',
  },
  {
    id: 'donkey kong',
    name: 'Donkey Kong GBA',
    categories: ['Casual'],
    url: './games/game.html?game=/RetroGames/Classic%20NES%20Donkey%20Kong.html',
    imgSrc: './cover/donkeykong.png',
  },
  {
    id: 'snes mario kart',
    name: 'SNES Mario Kart',
    categories: ['Casual', 'Driver'],
    url: './games/game.html?game=/RetroGames/smariokart.html',
    imgSrc: './cover/snesmariokart.png',
  },
  {
    id: 'super smash flash 2',
    name: 'Super Smash Flash 2',
    categories: ['Action'],
    url: './games/Flash.html?game=/Games11/super-smash-flash-2.swf',
    imgSrc: './cover/SuperSmash2.png',
  },
  {
    id: 'fall guys remake',
    name: 'Fall Guys Remake',
    categories: ['Casual'],
    url: './games/game.html?game=/Games11/StumbleGuysIG.html',
    imgSrc: './cover/fallg.png',
  },
  {
    id: 'the binding of isaac',
    name: 'The Binding Of Isaac',
    categories: ['Casual', 'Adventure'],
    url: './games/Flash.html?game=/Games11/the_binding_of_isaac.swf',
    imgSrc: './cover/isaacb.png',
  },
  {
    id: 'basketbros',
    name: 'BasketBros',
    categories: ['Sports'],
    url: './games/game.html?game=/Games11/basketbros',
    imgSrc: './cover/BASKETBRO.png',
  },
  {
    id: 'mortal kombat revelations',
    name: 'Mortal Kombat Revelations',
    categories: ['Action'],
    url: './games/game.html?game=/RetroGames/MortalKombatRevelations.html',
    imgSrc: './cover/mkrev.png',
  },
  {
    id: 'osu mania scratch',
    name: 'Osu Mania Scratch Version',
    categories: ['Casual'],
    url: './games/game.html?game=/Games11/Osu.html',
    imgSrc: './cover/osus.png',
  },
  {
    id: 'geometry dash',
    name: 'Geometry Dash (Better Version)',
    categories: ['Casual'],
    url: './games/game.html?game=/Games11/geometry-dash-lite',
    imgSrc: './cover/geo.jpeg',
  },
  {
    id: 'plants vs zombies',
    name: 'Plants Vs Zombies (Flash)',
    categories: ['Casual'],
    url: './games/Flash.html?game=/Games11/pvz.swf',
    imgSrc: './cover/pvz.png',
  },
  {
    id: 'gobble',
    name: 'Gobble',
    categories: ['Casual'],
    url: './games/game.html?game=/Games11/Gobble/Gobble.html',
    imgSrc: './cover/gobble.avif',
  },
  {
    id: 'dashcraft',
    name: 'DashCraft.io',
    categories: ['Driver'],
    url: './games/game.html?game=/Games11/dashcraft/index.html',
    imgSrc: './cover/dashcr.jfif',
  },
  {
    id: 'pacman',
    name: 'Pacman',
    categories: ['Casual'],
    url: './games/game.html?game=/pacman',
    imgSrc: './cover/pacman.jfif',
  },
  {
    id: 'idle breakout',
    name: 'Idle Breakout',
    categories: ['Casual', 'Idle'],
    url: './games/game.html?game=/Games11/idle-breakout/',
    imgSrc: './cover/idlebr.png',
  },
  {
    id: 'cluster truck',
    name: 'Cluster Truck (Fan Made)',
    categories: ['Casual'],
    url: './games/game.html?game=/Games11/cluster%20truck/',
    imgSrc: './cover/cluster.png',
  },
  {
    id: 'rocket pult',
    name: 'Rocket Pult',
    categories: ['Casual'],
    url: './games/game.html?game=/Games11/rocketp/',
    imgSrc: './cover/rocketp.png',
  },
  {
    id: 'magic tiles 3',
    name: 'Magic Tiles 3 (Clone)',
    categories: ['Casual'],
    url: './games/game.html?game=/Games11/magictiles/',
    imgSrc: './cover/magictiles.png',
  },
  {
    id: 'blumgi slime',
    name: 'Blumgi Slime',
    categories: ['Casual'],
    url: './games/game.html?game=/Games11/slime/Blumgi%20Slime.html',
    imgSrc: './cover/blumgisl.jpeg',
  },
  {
    id: 'the impossible quiz',
    name: 'The Impossible Quiz',
    categories: ['Casual'],
    url: './games/Flash.html?game=/Games11/The_Impossible_Quiz.swf',
    imgSrc: './cover/impqz.png',
  },
  {
    id: 'scrap metal 3',
    name: 'Scrap Metal 3',
    categories: ['Casual', 'Driver'],
    url: './games/game.html?game=/Games11/scrapmetal/',
    imgSrc: './cover/scrapm.jfif',
  },
  {
    id: 'bitburner',
    name: 'Bitburner',
    categories: ['Casual'],
    url: './games/game.html?game=/Games11/bitburner-dev/bitburner-dev/',
    imgSrc: './cover/bitburner.png',
  },
  {
    id: 'tube jumbers',
    name: 'Tube Jumpers',
    categories: ['Casual'],
    url: './games/game.html?game=/Games11/tube-jumpers',
    imgSrc: './cover/tubej.png',
  },
  {
    id: 'basket random',
    name: 'Basket Random',
    categories: ['Casual'],
    url: './games/game.html?game=/Games11/basketrandom',
    imgSrc: './cover/basketr.png',
  },
  {
    id: 'awesome tanks 2',
    name: 'Awesome Tanks 2',
    categories: ['Casual'],
    url: './games/game.html?game=/Games11/awesometanks2',
    imgSrc: './cover/tankawe2.png',
  },
  {
    id: 'boxing random',
    name: 'Boxing Random',
    categories: ['Casual'],
    url: './games/game.html?game=/Games11/boxingrandom',
    imgSrc: './cover/boxingr.png',
  },
  {
    id: 'duck life',
    name: 'Duck Life',
    categories: ['Casual'],
    url: './games/Flash.html?game=/Games11/ducklife1/game.swf',
    imgSrc: './cover/ducklife.avif',
  },
  {
    id: 'duck life 2',
    name: 'Duck Life 2',
    categories: ['Casual'],
    url: './games/Flash.html?game=/Games11/ducklife2/game.swf',
    imgSrc: './cover/ducklife.avif',
  },
  {
    id: 'duck life 3',
    name: 'Duck Life 3',
    categories: ['Casual'],
    url: './games/Flash.html?game=/Games11/ducklife3/game.swf',
    imgSrc: './cover/ducklife.avif',
  },
  {
    id: 'duck life 4',
    name: 'Duck Life 4',
    categories: ['Casual'],
    url: './games/Flash.html?game=/Games11/ducklife4/game.swf',
    imgSrc: './cover/ducklife.avif',
  },
  {
    id: 'run',
    name: 'Run',
    categories: ['Casual'],
    url: './games/Flash.html?game=/Games11/run1/game.swf',
    imgSrc: './cover/run1.png',
  },
  {
    id: 'worlds hardest game 3',
    name: 'Worlds Hardest Game 3',
    categories: ['Casual'],
    url: './games/Flash.html?game=/Games11/worldshardestgame3.swf',
    imgSrc: './cover/whg3.png',
  },
  {
    id: 'learn to fly 3',
    name: 'Learn To Fly 3',
    categories: ['Casual'],
    url: './games/Flash.html?game=/Games11/Learn-To-Fly-3.swf',
    imgSrc: './cover/ltf3.webp',
  },
  {
    id: 'cat tennis',
    name: 'Cat Tennis',
    categories: ['Casual'],
    url: './games/game.html?game=/Games11/cat tennis',
    imgSrc: './cover/cattennis.png',
  },
  {
    id: 'madness project nexus',
    name: 'Madness: Project Nexus (Classic)',
    categories: ['Casual'],
    url: './games/Flash.html?game=/Games11/madness.swf',
    imgSrc: './cover/madness.png',
  },
  {
    id: 'pizza tower',
    name: 'Pizza Tower',
    categories: ['Casual'],
    url: './games/game.html?game=/Games11/pizzatower',
    imgSrc: './cover/pizzatower.png',
  },
  {
    id: 'block blast',
    name: 'Block Blast (Clone)',
    categories: ['Casual'],
    url: './games/Flash.html?game=/Games11/blockblast/game.html',
    imgSrc: './cover/blockblast.jpg',
  },
  {
    id: 'polytrack',
    name: 'Polytrack',
    categories: ['Casual'],
    url: './games/Flash.html?game=/Games11/polytrack/index.html',
    imgSrc: './cover/polytrack.png',
  },
]

document.addEventListener('DOMContentLoaded', function () {
  const gamesContainer = document.getElementById('games')
  if (!gamesContainer) return

  gamesContainer.innerHTML = ''

  const isBeforeOpPage = window.location.pathname.endsWith('/beforeop.html')

  gamesData.forEach((game) => {
    const gameCard = document.createElement('div')
    gameCard.className = 'game-card'
    gameCard.setAttribute('id', game.id)
    gameCard.setAttribute('category', game.categories.join(' '))

    const gameLink = document.createElement('a')
    gameLink.href = game.url

    const thumbnailContainer = document.createElement('div')
    thumbnailContainer.className = 'thumbnail-container'

    const thumbnail = document.createElement('img')
    thumbnail.src = game.imgSrc
    thumbnail.alt = game.name
    thumbnail.className = isBeforeOpPage ? 'game-thumbnail' : 'ImageForGame'

    if (isBeforeOpPage) {
      thumbnail.loading = 'lazy'
      thumbnail.onerror = function () {
        this.onerror = null
        this.src = './fallback.png'
      }
    }

    thumbnailContainer.appendChild(thumbnail)

    const gameInfo = document.createElement('div')
    gameInfo.className = 'game-info'

    const gameTitle = document.createElement('h3')
    gameTitle.textContent = game.name

    gameInfo.appendChild(gameTitle)

    gameLink.appendChild(thumbnailContainer)
    gameLink.appendChild(gameInfo)

    gameCard.appendChild(gameLink)

    gamesContainer.appendChild(gameCard)
  })
})
